### PR TITLE
WIP: Authentication system (client side)

### PR DESCRIPTION
**Pull request by DanielLightbourn**
This has the client sign all data sent to the server. The infrastructure for generating new keys is complete but not in use. Because the back end isn't done yet, a test key is used.

Note: I changed the server address and port to the local host because it probably won't work with the api as of right now.

### CODE REVIEW

**Comment by r3pwn** [comment]
Regarding commit 30c18d76e43969a0c7e9b230799b09c1bd5b57bd, you don't need closing tags for meta, input, or img.

**Comment by r3pwn** [comment]
Regarding commit 613f0a56caa6247e3aaa0e57d2169532ed21b13b#diff-42f69825340f0b5fa628d80900a46daa, what happened to the formatting of the file?

**Comment by PrivacyPolicy** [comment]
I agree with @r3pwn, 613f0a56caa6247e3aaa0e57d2169532ed21b13b should be reverted. Those are empty elements and they don't need a closing tag.

**Comment by DanielLightbourn** [comment]
About the closing tags, for whatever reason, when I was working on this my browser was very picky about the html I was feeding it and refused to take anything without a closing tag (it was giving syntax errors).

The hardcoded key is there because the initial authentication isn’t done yet and the saving of the keys on the server isn’t done yet. It’ll be taken out once those are finished and a key will be generated randomly on initial authentication.

**Comment by r3pwn** [comment]
I still don't feel comfortable with merging this in its current state. It mangles one of the JavaScript files, doesn't merge cleanly at the moment, and has a ton of unnecessary stuff (empty commits, unnecessary closing tags, etc.).

**Comment by r3pwn** [comment]
I merged all of the important parts of this PR into the shiny, brand-new staging branch, as well as fixed a couple of minor complaints I had, while still retaining commit authorship. So, feel free to experiment with that a bit.

**Comment by r3pwn** [comment]
I'm not merging those last three commits.

**Comment by r3pwn** [comment]
Everything relevant to the authentication system has been merged into the staging branch. This PR is now closed.

**Pull request closed without merging**
